function showOnboarding() {
    document.body.classList.remove('signed-out'); document.getElementById('pageTitle').textContent = 'Set up your cluster'; document.getElementById('pageBreadcrumb').textContent = 'LabConnect / Onboarding'; renderSignedInChrome();
    document.getElementById('pages').innerHTML = `<div class="onboarding-layout"><div class="onboarding-heading"><span class="eyebrow">First-run setup</span><h2>Make this workspace yours.</h2><p>Name the head node and add the compute nodes it coordinates. You can change this data later.</p></div><form id="onboardingForm" class="card onboarding-card"><div class="form-group"><label for="workspaceName">Workspace name</label><input class="form-control" id="workspaceName" placeholder="My computing lab" required></div><div class="form-group"><label for="headHostname">Head node hostname</label><input class="form-control" id="headHostname" placeholder="lab-head-01" required></div><div class="form-group"><label for="nodeNames">Compute node hostnames <span class="hint">optional, one per line</span></label><textarea class="form-control" id="nodeNames" rows="5" placeholder="compute-01\ncompute-02\ncompute-03"></textarea></div><button class="btn btn-teal" type="submit">Connect workspace <i class="fas fa-arrow-right"></i></button><div id="onboardingError" class="mt-2"></div></form></div>`;
    document.getElementById('onboardingForm').onsubmit = event => {
        event.preventDefault();
        const workspaceName = document.getElementById('workspaceName').value.trim(); const headHostname = document.getElementById('headHostname').value.trim(); const names = document.getElementById('nodeNames').value.split('\n').map(name => name.trim()).filter(Boolean);
        if (!workspaceName || !headHostname) { document.getElementById('onboardingError').innerHTML = '<div class="alert alert-danger">Add a workspace name and head node hostname.</div>'; return; }
        LABS.splice(0, LABS.length, { id: 1, name: workspaceName, building: 'Local workspace', room: 'Cluster', total: names.length + 1 });
        computers = [{ id: 1, labId: 1, number: 'HEAD-01', hostname: headHostname, role: 'HEAD', os: 'Local agent', status: 'HEALTHY', online: true, network: 'CONNECTED', agent: 'RESPONDING', freeGB: null, totalGB: null, lastSeen: new Date().toISOString() }, ...names.map((hostname, index) => ({ id: index + 2, labId: 1, number: `NODE-${String(index + 1).padStart(2, '0')}`, hostname, role: 'COMPUTE', os: 'Unregistered', status: 'HEALTHY', online: true, network: 'UNKNOWN', agent: 'UNKNOWN', freeGB: null, totalGB: null, lastSeen: new Date().toISOString() }))];
        currentUser.onboarded = true; users = users.map(user => user.id === currentUser.id ? currentUser : user); const records = authRecords().map(record => record.id === currentUser.id ? { ...record, onboarded: true } : record); saveAuth(records); syncWorkspace(); renderSignedInChrome(); navigateTo('dashboard');
    };
}
