const fs = require('node:fs');
const assert = require('node:assert/strict');
(async()=>{
 const targets=await (await fetch('http://127.0.0.1:9222/json')).json();
 const socket=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);
 await new Promise(resolve=>socket.onopen=resolve);
 let sequence=0;const pending=new Map();const errors=[];
 socket.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result);}if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.text+': '+m.params.exceptionDetails.exception?.description);};
 const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++sequence;pending.set(id,{resolve,reject});socket.send(JSON.stringify({id,method,params}));});
 const evaluate=async expression=>{const result=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(result.exceptionDetails)throw new Error(result.exceptionDetails.exception.description);return result.result.value;};
 await send('Runtime.enable');await send('Page.enable');
 await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1100,deviceScaleFactor:1,mobile:false});
 await send('Page.navigate',{url:'http://127.0.0.1:8765/index.html'});
 for(let i=0;i<50;i++){if(await evaluate('!!document.querySelector(".agent-checks")'))break;await new Promise(r=>setTimeout(r,100));}
 assert.equal(await evaluate('document.querySelectorAll(".agent-check").length'),4);
 await evaluate('document.fonts.ready');
 fs.writeFileSync('preview-desktop.png',Buffer.from((await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true})).data,'base64'));
 await evaluate("navigateTo('monitoring')");
 assert.equal(await evaluate('document.querySelectorAll("#previewRows tr").length'),80);
 await evaluate("document.getElementById('previewSearch').value='LAB4-PC20';document.getElementById('previewSearch').dispatchEvent(new Event('input'))");
 assert.equal(await evaluate('document.querySelectorAll("#previewRows tr").length'),1);
 await evaluate("document.getElementById('previewSearch').value='no-match';document.getElementById('previewSearch').dispatchEvent(new Event('input'))");
 assert.match(await evaluate('document.getElementById("previewRows").textContent'),/No computers/);
 await evaluate("reportFaultForComputer(8);document.getElementById('reportType').value='Mouse Problem';document.getElementById('reportDesc').value='Mouse pointer freezes during class.';document.getElementById('reportNotes').value='USB mouse';document.getElementById('reportForm').requestSubmit()");
 assert.match(await evaluate('document.getElementById("reportResult").textContent'),/Report saved/);
 const report=await evaluate('faults.at(-1)');
 assert.equal(report.computerId,8);assert.equal(report.notes[0],'USB mouse');
 assert.equal(await evaluate('computers.find(c=>c.id===8).status'),'HEALTHY');
 await evaluate("navigateTo('myreports');setReportFilter('RESOLVED')");
 assert.equal(await evaluate('document.querySelectorAll("#pages tbody tr").length'),1);
 await evaluate("document.getElementById('previewRole').value='4';document.getElementById('previewRole').dispatchEvent(new Event('change'));navigateTo('faults');updateFaultStatus("+report.id+",'RESOLVED')");
 assert.equal(await evaluate('faults.find(f=>f.id==='+report.id+').status'),'RESOLVED');
 assert.equal(await evaluate('computers.find(c=>c.id===8).status'),'HEALTHY');
 await send('Page.reload');await new Promise(r=>setTimeout(r,700));
 assert.equal(await evaluate('faults.find(f=>f.id==='+report.id+').status'),'RESOLVED');
 await evaluate("localStorage.removeItem('labconnect-agent-faults-v1')");
 await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
 await evaluate("navigateTo('dashboard')");
 await new Promise(r=>setTimeout(r,350));
 assert.ok(await evaluate('document.documentElement.scrollWidth<=window.innerWidth'), 'Mobile should not overflow');
 assert.ok(await evaluate('document.getElementById("sidebar").getBoundingClientRect().right<=0'), 'Mobile navigation starts hidden');
 await evaluate('document.getElementById("sidebarToggle").click()');
 await new Promise(r=>setTimeout(r,350));
 assert.equal(await evaluate('document.getElementById("sidebar").classList.contains("open")'),true);
 await evaluate('document.getElementById("sidebarToggle").click()');
 await new Promise(r=>setTimeout(r,350));
 fs.writeFileSync('preview-mobile.png',Buffer.from((await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true})).data,'base64'));
 assert.deepEqual(errors,[]);
 console.log('PASS: desktop/mobile render, 80-device overview, search, empty state, report submission, notes, status filtering, administrator resolution, persistence, independent telemetry, no browser errors.');
 socket.close();
})().catch(e=>{console.error(e);process.exit(1)});
